### ISSUE TITLE
Ordering Collections as Navigation Items

### ISSUE THREAD

**Issue by bradonomics** [CloudCannon/Documentation#2]
I like the way you've ordered your collections as navigation items. I'd like to replicate this but can't get it to work in my project. It seems like the code doing the sorting is `{% assign items = collection.docs | sort: 'order' %}` in the [_includes/primary-nav.html](https://github.com/CloudCannon/Documentation/blob/master/_includes/primary-nav.html#L24) file. Any idea why it's only sorting in alphabetical order for me?

**Comment by bradonomics** [comment]
After more poking I realized that the `{% assign items = collection.docs | sort: 'order' %}` bit is for the collection's pages, not the collections themselves—and that part is working fine.

The part that's giving me trouble is the `{% for collection in site.collections %}` on [line 20](https://github.com/CloudCannon/Documentation/blob/master/_includes/primary-nav.html#L20). Instead of sorting in the order listed in the _config.yml file it's sorting in alphabetical order.

**Comment by mneumegen** [comment]
Hey Brad,

You should be able add an order field to the collection meta data in
_config.yml and then do a sort based on that. We do something similar in this
theme
https://github.com/CloudCannon/aviator-jekyll-theme/blob/master/_config.yml.
Have a look and if you need any further help let me know :-)
