### ISSUE TITLE
versions.md doesnt mention Ruby version

### ISSUE THREAD

**Issue by jayvdb** [CloudCannon/Documentation#7]
versions.md only mentions the Jekyll version.

My first site is failing to build because of
```
$ bundle install
Your Ruby version is 2.3.3, but your Gemfile specified 2.5.1
```

If there is no way to change the ruby version used, it would be useful to say that in the docs, here in versions and also on the Building page.

**Comment by rphillips-nz** [comment]
We usually just monitor our official support channel so this reply is a tad late!
Just for future readers, this is currently possible with https://docs.cloudcannon.com/builds/ruby-versions/
I'm not sure if this was present back in 2018, but better late than never.
